DISCORD:
  # Your discord bot token
  # More info about getting a bot token --------> https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token
  TOKEN: ''

GSPREAD:
  # The url for your google spreadsheet
  SHEET_URL: ''

STOCKS:
  # The list of stocks you want to check
  [
    'acgl',
    'amt',
    'aon',
    'awk',
    'bll',
    'cabo',
    'cdns',
    'cmg',
    'cost',
    'cprt',
    'csco',
    'fas',
    'faz',
    'fico',
    'gld',
    'ma',
    'mcd',
    'mco',
    'msft',
    'msi',
    'pg',
    'pgr',
    'pypl',
    'sbac',
    'sbux',
    'soxl',
    'soxs',
    'spy',
    'xlk',
    'trno',
    'tsn',
    'v'
  ]
